# Site settings
title: Unmatched parenthesis | On a journey to Clojure epiphany
description: "Yet another attempt to write something about Clojure on regular basis."
url: "http://unmatchedparenthesis.github.io"
author:
  name: "Andrzej Kimel"
  email: "andrzej.kimel@gmail.com"
  url: "http://unmatchedparenthesis.github.io"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Options
custom_header: true
custom_nav_footer: true
reverse: false
